# super user level permission
sudo: required
service:
  # make travils CI understand that we need docker CLI installed. then travis CI automatically install docker
  - docker


before_install:
  # build docker image before the test running
  # kensakuokada/docker-react == tag name of the future image. kensakuokada == docker user name. docker-react == github repository name
  - docker build -t kensakuokada/docker-react -f Dockerfile.dev .

script:
  # command necessary to run the test suite
  # -- --coverage: returning the test result and (important) automatically finish the test mode
  - docker run kensakuokada/docker-react npm run test -- --coverage

deploy:
  provider: elesticbeanstalk
  region: "eu-west-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-west-1-805857961942"
  bucket_path: "docker-react"
  # we deploy only when we deploy new code to master branch
  on:
    branch: master
  # set api keys of AWS (encrypted by travis CI)
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY



