version: '3'
services:
  web:
    # if we make "build" . , docker will look at Dockerfile.dev 
    build:
      # specify the directory to look for. "." means the current directory.
      context: .
      # specify the Dockerfile name to look at
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app
  # responsible for running a test
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
     # the placeholder where we make sure we never accidentally override that directory
      - /app/node_modules
      # map(override) the current directory to the app directory in the container
      - .:/app
    command: ["npm", "run", "test"]
    # command: ['nodemon', '--legacy-watch', '--exec', "npm", "run", "test"]

 